---
pterodactyl_panel_version: latest

pterodactyl_panel_webroot: /var/www/pterodactyl
pterodactyl_panel_domain: "{{ ansible_fqdn }}"
pterodactyl_panel_upload_limit: 100M

# Nginx or Apache ( default )
pterodactyl_panel_use_nginx: false

#==  SSL

pterodactyl_panel_ssl_mode: "none"          # == self signed... ===> this will not work well with wings no ?
# pterodactyl_panel_ssl_mode: "dehydrated"  # use dehydrated directory 
# -- other ?

# If SSL mode is 'dehydrated'
pterodactyl_panel_dehydrated_ssl_cert: "/var/lib/dehydrated/certs/{{ pterodactyl_panel_domain }}/fullchain.pem"
pterodactyl_panel_dehydrated_ssl_key:  "/var/lib/dehydrated/certs/{{ pterodactyl_panel_domain }}/privkey.pem"

# Let's encrypt acme or sefl-signed
pterodactyl_panel_ssl_cert: "{{ (pterodactyl_panel_ssl_mode == 'none') | ternary('/etc/letsencrypt/live/' + pterodactyl_panel_domain + '/fullchain.pem', '/etc/ssl/panel-selfsign.crt') }}"
pterodactyl_panel_ssl_key: "{{ (pterodactyl_panel_ssl_mode == 'none') | ternary('/etc/letsencrypt/live/' + pterodactyl_panel_domain + '/privkey.pem', '/etc/ssl/panel-selfsign.key') }}"


#pterodactyl_panel_app_key:
#pterodactyl_panel_hashids_salt:
pterodactyl_panel_timezone: America/New_York
pterodactyl_panel_locale: en
pterodactyl_panel_egg_author: "no-reply@{{ pterodactyl_panel_domain }}"
pterodactyl_panel_url: "https://{{ ansible_fqdn }}"
pterodactyl_panel_environment_only: true

pterodactyl_panel_db_host: "127.0.0.1"
pterodactyl_panel_db_port: 3306
pterodactyl_panel_db_name: panel
pterodactyl_panel_db_user: pterodactyl
#pterodactyl_panel_db_password:

pterodactyl_panel_mail_host: "127.0.0.1"
pterodactyl_panel_mail_port: 25
pterodactyl_panel_mail_user: ""
pterodactyl_panel_mail_password: ""
pterodactyl_panel_mail_encryption: ""
pterodactyl_panel_mail_from: "no-reply@{{ ansible_fqdn }}"
pterodactyl_panel_mail_from_name: Pterodactyl Panel

pterodactyl_panel_admin_mail: "admin@{{ ansible_fqdn }}"
pterodactyl_panel_admin_user: admin
pterodactyl_panel_admin_password: admin
pterodactyl_panel_admin_firstname: Admin
pterodactyl_panel_admin_lastname: Admin

# this var was renamed, preserve compatibility
pterodactyl_panel_backup_configure: "{{ pterodactyl_panel_backup_enable | default(false) }}"
pterodactyl_panel_backup_driver: s3

pterodactyl_panel_aws_endpoint: ""
pterodactyl_panel_aws_default_region: ""
pterodactyl_panel_aws_access_key_id: ""
pterodactyl_panel_aws_secret_access_key: ""
pterodactyl_panel_aws_backups_bucket: ""
