- name: Common dependency packages are installed
  ansible.builtin.package:
    name:
      - php-pdo
      - php-gd
      - php-mysql
      - php-pdo
      - php-mbstring
      - php-tokenizer
      - php-bcmath
      - php-xml
      - php-curl
      - php-zip
      - curl
      - unzip
      - git
      - redis-server
      # Needed to ensure that become_user to www-data works
      - acl


- name: Apache Dependency packages are installed
  when: pterodactyl_panel_use_nginx is false
  ansible.builtin.package:
    name:
      - apache2
      - libapache2-mod-php

- name: Dependency packages are installed ( Nginx )
  when: pterodactyl_panel_use_nginx is true
  ansible.builtin.package:
    name:
      - nginx
      - php-fpm

- name: Look for composer executable
  stat:
    path: /usr/local/bin/composer
  register: pterodactyl_panel_composer
- name: Install composer
  block:
  - name: Download composer install script
    get_url:
      url: https://getcomposer.org/installer
      dest: /tmp/composer
      owner: root
      group: root
      mode: "640"
  - name: Install composer # noqa no-changed-when
    command: php /tmp/composer --install-dir=/usr/local/bin --filename=composer
  - name: Installer script is absent
    file:
      path: /tmp/composer
      state: absent
  when: not pterodactyl_panel_composer.stat.exists
